import { Scenario, SimulationResult, AuditEventItem, BuyerMandate } from "../types";

export const DEMO_MANDATE: BuyerMandate = {
  mandate_id: "MANDATE-DEMO-001",
  max_budget_paise: 240000000, // ₹24,00,000 in integer paise
  currency: "INR",
  max_delivery_days: 7,
  allowed_categories: ["LAPTOP", "ACCESSORY", "MONITOR"],
  expires_at: "2028-12-31T23:59:59Z",
};

export const DEMO_SCENARIOS: Scenario[] = [
  {
    id: "volume_discount",
    name: "Volume Discount",
    icon: "⚡",
    tag: "Rescue Transaction",
    prompt: "Order 20 Lenovo IdeaPad laptops with a maximum budget of Rs. 24L.",
    description: "Catalog is Rs. 25L. ASC rescues with a 4% volume discount passing 16.67% margin floor.",
    normalized_request: {
      request_id: "REQ-VOL-001",
      product_query: "Lenovo IdeaPad Pro 16",
      quantity: 20,
      max_budget_paise: 240000000,
      currency: "INR",
      max_delivery_days: 7,
      hard_specs: {
        min_ram_gb: 16,
        min_cpu_tier: "i5",
        min_storage_gb: 512,
      },
      mandate_id: "MANDATE-DEMO-001",
    },
  },
  {
    id: "direct_match",
    name: "Direct Match",
    icon: "🎯",
    tag: "Standard Catalog",
    prompt: "Order 20 Lenovo IdeaPad laptops with a maximum budget of Rs. 27L.",
    description: "Catalog price fits within budget immediately. Standard direct offer generated.",
    normalized_request: {
      request_id: "REQ-DIR-002",
      product_query: "Lenovo IdeaPad Pro 16",
      quantity: 20,
      max_budget_paise: 270000000,
      currency: "INR",
      max_delivery_days: 7,
      hard_specs: {
        min_ram_gb: 16,
        min_cpu_tier: "i5",
        min_storage_gb: 512,
      },
      mandate_id: "MANDATE-DEMO-001",
    },
  },
  {
    id: "product_substitute",
    name: "Product Substitute",
    icon: "🔄",
    tag: "Spec-Compliant Swap",
    prompt: "Order 20 laptops with at least 16GB RAM and max budget of Rs. 22.5L.",
    description: "Requested SKU exceeds budget. ASC substitutes in-stock HP ProBook 450 (16GB RAM).",
    normalized_request: {
      request_id: "REQ-SUB-003",
      product_query: "Enterprise Laptop 16GB",
      quantity: 20,
      max_budget_paise: 225000000,
      currency: "INR",
      max_delivery_days: 7,
      hard_specs: {
        min_ram_gb: 16,
        min_cpu_tier: "i5",
        min_storage_gb: 512,
      },
      mandate_id: "MANDATE-DEMO-001",
    },
  },
  {
    id: "overstock_bundle",
    name: "Overstock Bundle",
    icon: "📦",
    tag: "Inventory Liquidation",
    prompt: "Order 20 Lenovo laptops with overstock accessories under Rs. 23.5L.",
    description: "Evaluates pairing with high-margin overstock mice to clear aging inventory.",
    normalized_request: {
      request_id: "REQ-BND-004",
      product_query: "Lenovo IdeaPad Pro 16",
      quantity: 20,
      max_budget_paise: 235000000,
      currency: "INR",
      max_delivery_days: 7,
      hard_specs: {
        min_ram_gb: 16,
        min_cpu_tier: "i5",
        min_storage_gb: 512,
      },
      mandate_id: "MANDATE-DEMO-001",
    },
  },
  {
    id: "impossible_deal",
    name: "Impossible Deal",
    icon: "🛑",
    tag: "Safety Rejection",
    prompt: "Order 50 Lenovo laptops with a maximum budget of Rs. 20L.",
    description: "Absurdly low buyer budget. MarginGate and BudgetGate fail; ASC safely rejects.",
    normalized_request: {
      request_id: "REQ-IMP-005",
      product_query: "Lenovo IdeaPad Pro 16",
      quantity: 50,
      max_budget_paise: 200000000,
      currency: "INR",
      max_delivery_days: 7,
      hard_specs: {
        min_ram_gb: 16,
        min_cpu_tier: "i5",
        min_storage_gb: 512,
      },
      mandate_id: "MANDATE-DEMO-001",
    },
  },
];

export const MOCK_SCENARIO_RESULTS: Record<string, { result: SimulationResult; auditEvents: AuditEventItem[] }> = {
  volume_discount: {
    result: {
      transaction_id: "TXN-VOL-84A2C1",
      rescued: true,
      catalog_price_paise: 250000000, // ₹25,00,000 in integer paise
      candidates: [
        {
          strategy: "VOLUME_DISCOUNT",
          name: "Tier 2 Enterprise Volume Pricing",
          total_price_paise: 240000000, // ₹24,00,000 in integer paise
          margin_percent: 16.67,
          discount_percent: 4.0,
          score: 36.27,
          status: "WINNER",
          note: "Meets exact Rs. 24L budget while beating 15.0% margin floor (16.67% >= 15.0%).",
        },
        {
          strategy: "PRODUCT_SUBSTITUTE",
          name: "HP ProBook 450 G10 Alternative",
          total_price_paise: 224000000,
          margin_percent: 19.64,
          discount_percent: 0.0,
          score: 35.86,
          status: "ALTERNATIVE",
          note: "Valid alternative, but requested brand SKU preferred by buyer preferences.",
        },
        {
          strategy: "BUNDLE_OVERSTOCK",
          name: "IdeaPad + Wireless Mouse Bundle",
          total_price_paise: 231000000,
          margin_percent: 12.81,
          discount_percent: 9.77,
          score: 0.0,
          status: "REJECTED_MARGIN",
          note: "Margin 12.81% falls below 15.0% policy floor — auto-disqualified by scoring engine.",
          gate_failure_reason: "MarginGate: 12.81% < 15.00% floor",
        },
      ],
      offer: {
        offer_id: "OFFER-VOL-01",
        transaction_id: "TXN-VOL-84A2C1",
        strategy: "VOLUME_DISCOUNT",
        explanation: "Applied 4.0% enterprise volume pricing on 20x Lenovo IdeaPad Pro 16 to meet buyer budget of Rs. 24,00,000.",
        catalog_price_paise: 250000000,
        total_price_paise: 240000000,
        margin_percent: 16.67,
        discount_percent: 4.0,
        final_score: 36.27,
        items: [
          {
            sku: "LAP-001",
            name: "Lenovo IdeaPad Pro 16",
            category: "LAPTOP",
            quantity: 20,
            unit_price_paise: 12000000, // ₹1,20,000
            total_price_paise: 240000000, // ₹24,00,000
            unit_cost_paise: 10000000, // ₹1,00,000
            total_cost_paise: 200000000, // ₹20,00,000
          },
        ],
      },
      gate_results: [
        {
          gate: "MarginGate",
          validation_target: "Ensures margin percent >= minimum floor",
          status: "PASS",
          expected: ">= 15.00%",
          actual: "16.67%",
          reason: "Offer profit margin (16.67%) meets merchant minimum floor (>= 15.00%).",
          metadata: { margin_percent: 16.67, min_margin_percent: 15.0 },
        },
        {
          gate: "InventoryGate",
          validation_target: "Verifies requested quantity <= DB stock",
          status: "PASS",
          expected: "Stock Available (<= 60)",
          actual: "20 / 60 Units In Stock",
          reason: "Verified SQLite DB inventory: 20 requested, 60 units in warehouse.",
          metadata: { requested: 20, available: 60 },
        },
        {
          gate: "BudgetGate",
          validation_target: "Confirms total price <= maximum budget",
          status: "PASS",
          expected: "<= 240000000 paise (Rs. 24L)",
          actual: "240000000 paise (Rs. 24L)",
          reason: "Offer total matches buyer authorized budget ceiling exactly.",
          metadata: { total_paise: 240000000, max_budget_paise: 240000000 },
        },
        {
          gate: "DiscountGate",
          validation_target: "Prevents discounts > policy ceiling",
          status: "PASS",
          expected: "<= 20.00%",
          actual: "4.00%",
          reason: "Applied discount (4.00%) strictly within merchant max cap (20.00%).",
          metadata: { discount_percent: 4.0, max_discount_percent: 20.0 },
        },
        {
          gate: "SpecificationGate",
          validation_target: "Validates hardware specification bounds",
          status: "PASS",
          expected: "RAM >= 16GB, CPU >= i5, Storage >= 512GB",
          actual: "16GB RAM, i7-13700H, 1TB SSD",
          reason: "All hardware specifications meet or exceed buyer constraints.",
          metadata: { ram_gb: 16, cpu: "i7-13700H", storage_gb: 1024 },
        },
        {
          gate: "MandateGate",
          validation_target: "Checks buyer agent authorization limits",
          status: "PASS",
          expected: "Mandate Active & Authorized",
          actual: "MANDATE-DEMO-001 (Valid)",
          reason: "Offer complies with Buyer Agent Mandate (Cap: Rs. 24L, Active to 2028).",
          metadata: { mandate_id: "MANDATE-DEMO-001", authorized: true },
        },
      ],
      message: "Transaction rescued successfully! Counteroffer approved by Deterministic Control Plane.",
      buyer_decision: {
        status: "ACCEPTED",
        reason: "Counteroffer matches budget cap (Rs. 24,00,000), delivers requested Lenovo SKU, and satisfies all hard specs.",
        mandate_compliant: true,
      },
    },
    auditEvents: [
      {
        timestamp: "12:00:01",
        component: "INTENT_PARSER",
        event_type: "INTENT_PARSED",
        status: "INFO",
        message: "Buyer prompt normalized into structured request: 20x Lenovo IdeaPad, max budget 240000000 paise (Rs. 24,00,000).",
        metadata: { max_budget_paise: 240000000, quantity: 20 },
      },
      {
        timestamp: "12:00:02",
        component: "ASC_ORCHESTRATOR",
        event_type: "DIRECT_MATCH_FAILED",
        status: "WARN",
        message: "Direct match failed: Catalog price 250000000 paise exceeds buyer budget 240000000 paise. Transaction at risk!",
        metadata: { catalog_price_paise: 250000000, budget_paise: 240000000 },
      },
      {
        timestamp: "12:00:03",
        component: "STRATEGY_ENGINE",
        event_type: "CANDIDATES_GENERATED",
        status: "INFO",
        message: "Generated 3 candidate packages: VOLUME_DISCOUNT, PRODUCT_SUBSTITUTE, BUNDLE_OVERSTOCK.",
      },
      {
        timestamp: "12:00:04",
        component: "SCORING_ENGINE",
        event_type: "MARGIN_GATE_REJECTION",
        status: "WARN",
        message: "Candidate BUNDLE_OVERSTOCK yielded 12.81% margin below 15.0% floor. Assigned score 0.00.",
        metadata: { candidate: "BUNDLE_OVERSTOCK", margin_percent: 12.81, min_floor: 15.0 },
      },
      {
        timestamp: "12:00:04",
        component: "SCORING_ENGINE",
        event_type: "WINNER_RANKED",
        status: "INFO",
        message: "Winning strategy selected: VOLUME_DISCOUNT (Final Score: 36.27/100, Margin: 16.67%).",
      },
      {
        timestamp: "12:00:05",
        component: "MARGIN_GATE",
        event_type: "GATE_CHECK_PASS",
        status: "PASS",
        message: "[MarginGate] 16.67% >= 15.00% floor. PASS.",
        metadata: { margin_percent: 16.67, min_margin: 15.0 },
      },
      {
        timestamp: "12:00:05",
        component: "INVENTORY_GATE",
        event_type: "GATE_CHECK_PASS",
        status: "PASS",
        message: "[InventoryGate] 20 units requested, 60 units available in stock. PASS.",
      },
      {
        timestamp: "12:00:05",
        component: "BUDGET_GATE",
        event_type: "GATE_CHECK_PASS",
        status: "PASS",
        message: "[BudgetGate] 240000000 paise <= 240000000 paise ceiling. PASS.",
      },
      {
        timestamp: "12:00:05",
        component: "DISCOUNT_GATE",
        event_type: "GATE_CHECK_PASS",
        status: "PASS",
        message: "[DiscountGate] 4.00% <= 20.00% max cap. PASS.",
      },
      {
        timestamp: "12:00:05",
        component: "SPECIFICATION_GATE",
        event_type: "GATE_CHECK_PASS",
        status: "PASS",
        message: "[SpecificationGate] RAM (16GB), CPU (i7), Storage (1TB) compliant. PASS.",
      },
      {
        timestamp: "12:00:05",
        component: "MANDATE_GATE",
        event_type: "GATE_CHECK_PASS",
        status: "PASS",
        message: "[MandateGate] Authorized under MANDATE-DEMO-001. PASS.",
      },
      {
        timestamp: "12:00:06",
        component: "CONTROL_PLANE",
        event_type: "OFFER_APPROVED",
        status: "PASS",
        message: "Offer OFFER-VOL-01 passed all 6 gates. APPROVED by Commerce Control Plane.",
      },
    ],
  },
  direct_match: {
    result: {
      transaction_id: "TXN-DIR-11F890",
      rescued: true,
      catalog_price_paise: 250000000,
      candidates: [
        {
          strategy: "DIRECT_CATALOG_MATCH",
          name: "Standard Catalog Order",
          total_price_paise: 250000000,
          margin_percent: 20.0,
          discount_percent: 0.0,
          score: 42.0,
          status: "WINNER",
          note: "Buyer budget of Rs. 27L readily accommodates catalog price of Rs. 25L.",
        },
      ],
      offer: {
        offer_id: "OFFER-DIR-01",
        transaction_id: "TXN-DIR-11F890",
        strategy: "DIRECT_CATALOG_MATCH",
        explanation: "Standard catalog match: 20x Lenovo IdeaPad Pro 16 at list price Rs. 1,25,000 each.",
        catalog_price_paise: 250000000,
        total_price_paise: 250000000,
        margin_percent: 20.0,
        discount_percent: 0.0,
        final_score: 42.0,
        items: [
          {
            sku: "LAP-001",
            name: "Lenovo IdeaPad Pro 16",
            category: "LAPTOP",
            quantity: 20,
            unit_price_paise: 12500000,
            total_price_paise: 250000000,
            unit_cost_paise: 10000000,
            total_cost_paise: 200000000,
          },
        ],
      },
      gate_results: [
        { gate: "MarginGate", validation_target: "Ensures margin percent >= minimum floor", status: "PASS", expected: ">= 15.00%", actual: "20.00%", reason: "List catalog margin is 20.00%." },
        { gate: "InventoryGate", validation_target: "Verifies requested quantity <= DB stock", status: "PASS", expected: "Stock Available", actual: "20 / 60 Units In Stock", reason: "Stock verified in warehouse." },
        { gate: "BudgetGate", validation_target: "Confirms total price <= maximum budget", status: "PASS", expected: "<= 270000000 paise", actual: "250000000 paise", reason: "Catalog price is well under Rs. 27L budget." },
        { gate: "DiscountGate", validation_target: "Prevents discounts > policy ceiling", status: "PASS", expected: "<= 20.00%", actual: "0.00%", reason: "Zero discount applied on standard catalog." },
        { gate: "SpecificationGate", validation_target: "Validates hardware specification bounds", status: "PASS", expected: "RAM >= 16GB", actual: "16GB RAM", reason: "Direct SKU matches all specs." },
        { gate: "MandateGate", validation_target: "Checks buyer agent authorization limits", status: "PASS", expected: "Authorized", actual: "Valid Mandate", reason: "Authorized under demo mandate." },
      ],
      message: "Standard catalog match found! Approved without discount.",
      buyer_decision: {
        status: "ACCEPTED",
        reason: "Catalog price of Rs. 25,00,000 fits comfortably within Rs. 27,00,000 budget cap.",
        mandate_compliant: true,
      },
    },
    auditEvents: [
      { timestamp: "12:00:01", component: "INTENT_PARSER", event_type: "INTENT_PARSED", status: "INFO", message: "Parsed: 20x Lenovo IdeaPad with Rs. 27L budget (270000000 paise)." },
      { timestamp: "12:00:02", component: "ASC_ORCHESTRATOR", event_type: "DIRECT_MATCH_SUCCESS", status: "PASS", message: "Catalog price (250000000 paise) <= Budget (270000000 paise). Direct Match viable." },
      { timestamp: "12:00:03", component: "CONTROL_PLANE", event_type: "OFFER_APPROVED", status: "PASS", message: "All 6 gates validated. Direct offer approved." },
    ],
  },
  product_substitute: {
    result: {
      transaction_id: "TXN-SUB-49C772",
      rescued: true,
      catalog_price_paise: 250000000,
      candidates: [
        {
          strategy: "PRODUCT_SUBSTITUTE",
          name: "HP ProBook 450 G10 Substitution",
          total_price_paise: 224000000,
          margin_percent: 19.64,
          discount_percent: 0.0,
          score: 37.4,
          status: "WINNER",
          note: "Meets tight Rs. 22.5L budget with compliant 16GB RAM and 19.64% margin.",
        },
      ],
      offer: {
        offer_id: "OFFER-SUB-01",
        transaction_id: "TXN-SUB-49C772",
        strategy: "PRODUCT_SUBSTITUTE",
        explanation: "Substituted with in-stock alternative HP ProBook 450 G10 (16GB RAM / 512GB SSD) meeting budget cap Rs. 22,50,000.",
        catalog_price_paise: 250000000,
        total_price_paise: 224000000,
        margin_percent: 19.64,
        discount_percent: 0.0,
        final_score: 37.4,
        items: [
          {
            sku: "LAP-002",
            name: "HP ProBook 450 G10",
            category: "LAPTOP",
            quantity: 20,
            unit_price_paise: 11200000,
            total_price_paise: 224000000,
            unit_cost_paise: 9000000,
            total_cost_paise: 180000000,
          },
        ],
      },
      gate_results: [
        { gate: "MarginGate", validation_target: "Ensures margin percent >= minimum floor", status: "PASS", expected: ">= 15.00%", actual: "19.64%", reason: "Margin 19.64% exceeds floor." },
        { gate: "InventoryGate", validation_target: "Verifies requested quantity <= DB stock", status: "PASS", expected: "In Stock", actual: "20 / 45 Units In Stock", reason: "Stock verified for LAP-002." },
        { gate: "BudgetGate", validation_target: "Confirms total price <= maximum budget", status: "PASS", expected: "<= 225000000 paise", actual: "224000000 paise", reason: "Fits within Rs. 22.5L limit." },
        { gate: "DiscountGate", validation_target: "Prevents discounts > policy ceiling", status: "PASS", expected: "<= 20.00%", actual: "0.00%", reason: "Standard list price on substitute SKU." },
        { gate: "SpecificationGate", validation_target: "Validates hardware specification bounds", status: "PASS", expected: "RAM >= 16GB, Storage >= 512GB", actual: "16GB RAM, 512GB SSD", reason: "SpecificationGate confirms substitute has 16GB RAM (Compliant)." },
        { gate: "MandateGate", validation_target: "Checks buyer agent authorization limits", status: "PASS", expected: "Authorized", actual: "Valid Mandate", reason: "Complies with category and amount mandate." },
      ],
      message: "Deal rescued via spec-compliant hardware substitution!",
      buyer_decision: {
        status: "ACCEPTED",
        reason: "HP ProBook 450 matches all hard spec constraints (16GB RAM) and fits within Rs. 22.5L budget.",
        mandate_compliant: true,
      },
    },
    auditEvents: [
      { timestamp: "12:00:01", component: "INTENT_PARSER", event_type: "INTENT_PARSED", status: "INFO", message: "Parsed: 20x laptops with >=16GB RAM under Rs. 22.5L." },
      { timestamp: "12:00:02", component: "SPECIFICATION_GATE", event_type: "SPEC_VERIFIED", status: "PASS", message: "HP ProBook 450 verified: 16GB RAM matches requirement." },
      { timestamp: "12:00:03", component: "CONTROL_PLANE", event_type: "OFFER_APPROVED", status: "PASS", message: "Substitute package approved." },
    ],
  },
  overstock_bundle: {
    result: {
      transaction_id: "TXN-BND-66E319",
      rescued: true,
      catalog_price_paise: 250000000,
      candidates: [
        {
          strategy: "BUNDLE_OVERSTOCK",
          name: "IdeaPad + Wireless Mouse Overstock Bundle",
          total_price_paise: 235000000,
          margin_percent: 15.2,
          discount_percent: 6.8,
          score: 34.8,
          status: "WINNER",
          note: "Liquidates 20 aging overstock mouse units while preserving 15.2% margin.",
        },
      ],
      offer: {
        offer_id: "OFFER-BND-01",
        transaction_id: "TXN-BND-66E319",
        strategy: "BUNDLE_OVERSTOCK",
        explanation: "Bundled 20x Lenovo IdeaPad Pro 16 with 20x overstock Wireless Mice, meeting budget Rs. 23.5L.",
        catalog_price_paise: 250000000,
        total_price_paise: 235000000,
        margin_percent: 15.2,
        discount_percent: 6.8,
        final_score: 34.8,
        items: [
          {
            sku: "LAP-001",
            name: "Lenovo IdeaPad Pro 16",
            category: "LAPTOP",
            quantity: 20,
            unit_price_paise: 11500000,
            total_price_paise: 230000000,
            unit_cost_paise: 10000000,
            total_cost_paise: 200000000,
          },
          {
            sku: "ACC-001",
            name: "Wireless Optical Mouse (Overstock)",
            category: "ACCESSORY",
            quantity: 20,
            unit_price_paise: 250000,
            total_price_paise: 5000000,
            unit_cost_paise: 100000,
            total_cost_paise: 2000000,
            is_overstock: true,
          },
        ],
      },
      gate_results: [
        { gate: "MarginGate", validation_target: "Ensures margin percent >= minimum floor", status: "PASS", expected: ">= 15.00%", actual: "15.20%", reason: "Blended bundle margin meets floor (15.2% >= 15.0%)." },
        { gate: "InventoryGate", validation_target: "Verifies requested quantity <= DB stock", status: "PASS", expected: "All in stock", actual: "Laptops: 20/60, Mice: 20/120", reason: "Overstock inventory readily available." },
        { gate: "BudgetGate", validation_target: "Confirms total price <= maximum budget", status: "PASS", expected: "<= 235000000 paise", actual: "235000000 paise", reason: "Matches buyer ceiling." },
        { gate: "DiscountGate", validation_target: "Prevents discounts > policy ceiling", status: "PASS", expected: "<= 20.00%", actual: "6.80%", reason: "Discount cap respected." },
        { gate: "SpecificationGate", validation_target: "Validates hardware specification bounds", status: "PASS", expected: "Specs Compliant", actual: "All Specs Compliant", reason: "Main hardware meets specs." },
        { gate: "MandateGate", validation_target: "Checks buyer agent authorization limits", status: "PASS", expected: "Allowed Categories", actual: "LAPTOP, ACCESSORY", reason: "Both item categories permitted in mandate." },
      ],
      message: "Overstock bundle created! Successfully cleared aging inventory at safe margins.",
      buyer_decision: {
        status: "ACCEPTED",
        reason: "Bundle delivers required laptops plus complimentary accessories under budget cap.",
        mandate_compliant: true,
      },
    },
    auditEvents: [
      { timestamp: "12:00:01", component: "INTENT_PARSER", event_type: "INTENT_PARSED", status: "INFO", message: "Parsed overstock bundle request." },
      { timestamp: "12:00:02", component: "OVERSTOCK_GENERATOR", event_type: "BUNDLE_ASSEMBLED", status: "INFO", message: "Paired LAP-001 with aging stock ACC-001." },
      { timestamp: "12:00:03", component: "CONTROL_PLANE", event_type: "OFFER_APPROVED", status: "PASS", message: "Bundle approved by Control Plane." },
    ],
  },
  impossible_deal: {
    result: {
      transaction_id: "TXN-FAIL-009D41",
      rescued: false,
      catalog_price_paise: 625000000, // 50 * 1,25,000 = Rs. 62.5L
      candidates: [
        {
          strategy: "VOLUME_DISCOUNT",
          name: "Extreme Volume Discount Attempt",
          total_price_paise: 200000000,
          margin_percent: -60.0,
          discount_percent: 68.0,
          score: 0.0,
          status: "REJECTED_MARGIN",
          note: "Breaches both 15% margin floor (-60%) and 20% max discount cap (68%).",
          gate_failure_reason: "MarginGate: -60.0% < 15.0% & DiscountGate: 68% > 20%",
        },
      ],
      offer: null,
      gate_results: [
        {
          gate: "MarginGate",
          validation_target: "Ensures margin percent >= minimum floor",
          status: "FAIL",
          expected: ">= 15.00%",
          actual: "-60.00%",
          reason: "Offer severely violates merchant minimum profit floor (-60.0% < 15.00%).",
          metadata: { margin_percent: -60.0, min_margin_percent: 15.0 },
        },
        {
          gate: "InventoryGate",
          validation_target: "Verifies requested quantity <= DB stock",
          status: "FAIL",
          expected: "50 Units in stock",
          actual: "25 Units In Stock",
          reason: "Requested quantity (50) exceeds current warehouse stock (25).",
          metadata: { requested: 50, available: 25 },
        },
        {
          gate: "BudgetGate",
          validation_target: "Confirms total price <= maximum budget",
          status: "FAIL",
          expected: "<= 200000000 paise (Rs. 20L)",
          actual: "625000000 paise (Rs. 62.5L)",
          reason: "Minimum viable merchant cost exceeds buyer budget by Rs. 42.5 Lakhs.",
          metadata: { cost_paise: 500000000, budget_paise: 200000000 },
        },
        {
          gate: "DiscountGate",
          validation_target: "Prevents discounts > policy ceiling",
          status: "FAIL",
          expected: "<= 20.00%",
          actual: "68.00%",
          reason: "Required price cut of 68.00% breaches merchant policy ceiling of 20.00%.",
          metadata: { required_discount: 68.0, max_discount: 20.0 },
        },
        {
          gate: "SpecificationGate",
          validation_target: "Validates hardware specification bounds",
          status: "PASS",
          expected: "RAM >= 16GB",
          actual: "16GB RAM",
          reason: "Hardware specs compliant.",
        },
        {
          gate: "MandateGate",
          validation_target: "Checks buyer agent authorization limits",
          status: "FAIL",
          expected: "Within Mandate Cap",
          actual: "Breaches Ceiling",
          reason: "Requested deal exceeds buyer agent demo mandate ceiling.",
        },
      ],
      message: "No candidate satisfies buyer budget while maintaining merchant's 15% minimum margin floor. Gracefully rejected.",
      buyer_decision: {
        status: "REJECTED",
        reason: "Merchant rejected transaction safely. Required commercial terms would result in severe financial loss.",
        mandate_compliant: false,
      },
    },
    auditEvents: [
      { timestamp: "12:00:01", component: "INTENT_PARSER", event_type: "INTENT_PARSED", status: "INFO", message: "Parsed: 50x laptops for Rs. 20L budget (200000000 paise)." },
      { timestamp: "12:00:02", component: "MARGIN_GATE", event_type: "GATE_FAIL", status: "FAIL", message: "[MarginGate] Projected margin -60% < 15% floor. HARD STOP." },
      { timestamp: "12:00:03", component: "CONTROL_PLANE", event_type: "TRANSACTION_REJECTED", status: "FAIL", message: "Merchant profit safety prioritized. Zero bad trades executed." },
    ],
  },
};
